// const BIG = "big",
//   H = "horizontal",
//   V = "vertical",
//   HUGE = "huge";

export const listOfSculptures = [
  {
    id: "1",
    title:  "SPRING",
    source: "cos1.jpg",
    description:"A two figure life-sized bronze piece shows college-aged students situated in poses as if studying between classes. Created in 1979, it was installed in 1998, donated by Richard Fitton in honor of his parents.",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: HUGE,
  },
  {
    id: "2",
    title:  "SHARED VISION",
    source: "cos2.jpg",
    description:"Placed in 1997, a seated female figure in casual dress has sunglasses in her outstretched right hand. Her left hand holds her place in a book as shegestures as if offering the glasses,i.e. Shared Vision. ",
    artist:" Fred Brownstein",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "3",
    title:  "FIRST RIDE",
    source: "cos3.jpg",
    description:"The work, by the internationally known sculptor, is a classic event: a girl, seated on a bicycle, attempting her first ride as her father stands proudly behind her.  Sponsored by the Carruthers family and unveiled in 1997. ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: HUGE,
    },
  {
    id: "4",
    title:  "FIREFIGHTER MEMORIAL",
    source: "cos4.jpg",
    description:"The Butler County Fire Chiefs Association commissioned this memorial to those’lost in the line of duty. Public & private’donations paid for it along with the plaque honoring 15 Butler County’firefighters and EMTs who died’serving others.   ",
    artist:"George Danhires",
    address:"Pioneer Park, Monument Ave.",
    // size: H,
  },
  {
    id: "5",
    title:  "PIONEER FAMILY",
    source: "cos5.jpg",
    description:"Donated by Dr. John A. Stewart’and his wife, Marian Vail Stewart, to’commemorate the 200th anniversary of the Stewart family settling in Hamilton.  The faces are based on the Stewarts’at age 25. Installed September 2002. ",
    artist:" Jerry Hawkins",
    address:"Monument Cabin on Monument Ave.",
    // size: HUGE,
  },
  {
    id: "6",
    title:  "VICTORY",
    source: "cos6.jpg",
    description:" Victory, a 17’. 3500-lb. bronze Civil War soldier, was installed in 1906 on the Soldiers, Sailors, and Pioneers Monument.  His design was selected after a national competition.",
    artist:"Rudolph Thiem",
    address:"High St. & Monument Ave.",
    // size: V,
  },
  {
    id: "7",
    title:  "LEGACY OF LITERATURE",
    source: "cos7.jpg",
    description:"Purchased by Dr. & Mrs. James Stewart for the City of Sculpture, this bronze piece is a tribute to the thirst for knowledge through reading. The sculpture was installed April 2002 in the plaza at One High Street.",
    artist:"Rosalind Cook",
    address:"High St. at Monument Ave.",
    // size: BIG,
  },
  {
    id: "8",
    title:  "KITTY BENCH",
    source: "cos8.jpg",
    description:" ",
    artist:" ",
    address:" ",
    // size: H,
  },
  {
    id: "9",
    title:  "DOUBLE CRAZY SWIRL",
    source: "cos9.jpg",
    description:"This is a colorful kinetic sculpture on a stainless steel base. Given to the City of Sculpture from Sherry Armstead and Symmetry Boutique.",
    artist:" Andrew Carson",
    address:"In front of the Visitor Center",
    // size: V,
  },
  {
    id: "10",
    title:  "LENTIL",
    source: "cos10.jpg",
    description:" In the 1940s children’s book by Hamilton native Robert McCloskey, Lentil parades through town, harmonica and dog in tow.  The Hamilton Community Foundation funded this as one of many permanent legacy gifts to the city.",
    artist:"Nancy Schon",
    address:"NW Corner - High at Front St.",
    // size: H,
  },
  {
    id: "11",
    title:  "SNAPSHOT",
    source: "cos11.jpg",
    description:" This life-size sculpture of seven children assembled to have their picture taken was commissioned by the Butler County Commissioners in September 2001.",
    artist:"Jane DeDecker",
    address:"County Administration Center, 130 High St.",
    // size: H,
  },
  {
    id: "12",
    title:  "URBAN RENEWAL",
    source: "cos12.jpg",
    description:" Local artist Nick Bauer contrasts Hamilton’s industrial past and bright future with the juxtaposition of the oxidized Cor-Ten base and use of stainless steel. This was purchased by Jim ",
    artist:"Nick Bauer",
    address:"Market St. & 2nd",
    // size: V,
  },
  {
    id: "13",
    title:  "PARK PLACE",
    source: "cos13.jpg",
    description:"This installation of 6 life-sized figures was created by world-famous artist, Glenna Goodacre. The artist brings her sense of fun to this interactive piece donated in 2007 by Sarah and Joe Marcum. ",
    artist:"Glenna Goodacre",
    address:"SW Corner of the High/Main St. Bridge",
    // size: H,
  },
  {
    id: "14",
    title:  "RESURGENCE",
    source: "cos14.jpg",
    description:"This welded metal sculpture was the winner of an Open Call to Artists competition in 2009. The sculptor took home the grand prize of $10,000 from the Outdoor Sculpture Exhibition. ",
    artist:" Jonathan Hils",
    address:"RiversEdge",
    // size: BIG,
  },
  {
    id: "15",
    title:  "4 PEOPLE",
    source: "cos15.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "16",
    title:  "GUITAR",
    source: "cos16.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "17",
    title:  "MARCUM IN THE PARK",
    source: "cos17.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "18",
    title:  "DOUBLE DANCER",
    source: "cos18.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "19",
    title:  "TREE BENCH",
    source: "cos19.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "20",
    title:  "THE MAESTRO",
    source: "cos20.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "21",
    title:  "BIRD HOUSE",
    source: "cos21.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "22",
    title:  "REPUBLIC CAR",
    source: "cos22.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "23",
    title:  "A FOREST TREASURE",
    source: "cos23.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "24",
    title:  "LET'S RIDE",
    source: "cos24.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "25",
    title:  "KEEPER OF THE GARDEN",
    source: "cos25.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "26",
    title:  "HERE",
    source: "cos26.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "27",
    title:  "THE HAMILTON GATEWAY",
    source: "cos27.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "28",
    title:  "THE AMERICAN CAPE",
    source: "cos28.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "29",
    title:  "CONVERSATION IN SIX PARTS",
    source: "cos29.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "30",
    title:  "COLLECTIVE IMPACT",
    source: "cos30.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "31",
    title:  "COME UNTO ME",
    source: "cos31.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "32",
    title:  "HANNA",
    source: "cos32.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "33",
    title:  "BRIDGE MEDALLIONS (1-4)",
    source: "cos33.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
  },
  {
    id: "34",
    title:  "RIVERSIDE MALLARDS",
    source: "cos34.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "35",
    title:  "RIVER FLOOD MARKER",
    source: "cos35.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "36",
    title:  "FAMILY OF MAN",
    source: "cos36.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "37",
    title:  "TULIPS FOR THERESA BENCH",
    source: "cos37.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: HUGE,
  },
  {
    id: "38",
    title:  "EMBRACE",
    source: "cos38.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
  },
  {
    id: "39",
    title:  "WHEN IT RAINS IT POURS",
    source: "cos39.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "40",
    title:  "BEETLE BENCH",
    source: "cos40.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "41",
    title:  "TWO HALVES OF A WHOLE",
    source: "cos41.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "42",
    title:  "SHERRY CORBET MEMORIAL",
    source: "cos42.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "43",
    title:  "SPACE TOWER",
    source: "cos43.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "44",
    title:  "BRIDGE MEDALLIONS (5-8)",
    source: "cos33.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "45",
    title:  "HELIOS GUARDIANS",
    source: "heliosGuardians.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "46",
    title:  "HOLE IN THE EARTH",
    source: "holeInTheEarth.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "47",
    title:  "LEARN AND GROW TOGETHER",
    source: "learnAndGrowTogether.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "48",
    title:  "MILLIKIN WOODS TOTEM POLE",
    source: "millikinWoodsTotemPole.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "49",
    title:  "NO CHILD LEFT BEHIND",
    source: "noChildLeftBehind.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "50",
    title:  "SPACE TOWER",
    source: "passages.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: HUGE,
  },
  {
    id: "51",
    title:  "PEACE OFFICER MEMORIAL",
    source: "peaceOfficerMemorial.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "52",
    title:  "SOMEDAY",
    source: "someday.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: H,
  },
  {
    id: "53",
    title:  "STAR FORMATION",
    source: "starFormation.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "54",
    title:  "THE HAPPY FAMILY",
    source: "theHappyFamily.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },
  {
    id: "55",
    title:  "TORRENT",
    source: "torrent.jpg",    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: BIG,
  },

  {
    id: "56",
    title:  "WILLOW",
    source: "willow.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "57",
    title:  "WIND FOREST",
    source: "windforest.jpg",
    description:" ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },

];