// const BIG = "big",
//   H = "horizontal",
//   V = "vertical",
//   HUGE = "huge";

export const listOfSculptures = [
  {
    id: "1",
    title:  "SPRING",
    source: "cos1.jpg",
    artist: "Name of Artist",
    address: "Address of Sculpture",
    description: "Description of Sculpture"
    // size: HUGE,
  },
  {
    id: "2",
    title:  "SHARED VISION",
    source: "cos2.jpg",
    // size: V,
  },
  {
    id: "3",
    title:  "FIRST RIDE",
    source: "cos3.jpg",
    // size: HUGE,
    },
  {
    id: "4",
    title:  "FIREFIGHTER MEMORIAL",
    source: "cos4.jpg",
    // size: H,
  },
  {
    id: "5",
    title:  "PIONEER FAMILY",
    source: "cos5.jpg",
    // size: HUGE,
  },
  {
    id: "6",
    title:  "VICTORY",
    source: "cos6.jpg",
    // size: V,
  },
  {
    id: "7",
    title:  "LEGACY OF LITERATURE",
    source: "cos7.jpg",
    // size: BIG,
  },
  {
    id: "8",
    title:  "KITTY BENCH",
    source: "cos8.jpg",
    // size: H,
  },
  {
    id: "9",
    title:  "DOUBLE CRAZY SWIRL",
    source: "cos9.jpg",
    // size: V,
  },
  {
    id: "10",
    title:  "LENTIL",
    source: "cos10.jpg",
    // size: H,
  },
  {
    id: "11",
    title:  "SNAPSHOT",
    source: "cos11.jpg",
    // size: H,
  },
  {
    id: "12",
    title:  "URBAN RENEWAL",
    source: "cos12.jpg",
    // size: V,
  },
  {
    id: "13",
    title:  "PARK PLACE",
    source: "cos13.jpg",
    // size: H,
  },
  {
    id: "14",
    title:  "RESURGENCE",
    source: "cos14.jpg",
    // size: BIG,
  },
  {
    id: "15",
    title:  "4 PEOPLE",
    source: "cos15.jpg",
    // size: H,
  },
  {
    id: "16",
    title:  "GUITAR",
    source: "cos16.jpg",
    // size: V,
  },
  {
    id: "17",
    title:  "MARCUM IN THE PARK",
    source: "cos17.jpg",
    // size: V,
  },
  {
    id: "18",
    title:  "DOUBLE DANCER",
    source: "cos18.jpg",
    // size: BIG,
  },
  {
    id: "19",
    title:  "TREE BENCH",
    source: "cos19.jpg",
    // size: H,
  },
  {
    id: "20",
    title:  "THE MAESTRO",
    source: "cos20.jpg",
    // size: H,
  },
  {
    id: "21",
    title:  "BIRD HOUSE",
    source: "cos21.jpg",
    // size: V,
  },
  {
    id: "22",
    title:  "REPUBLIC CAR",
    source: "cos22.jpg",
    // size: H,
  },
  {
    id: "23",
    title:  "A FOREST TREASURE",
    source: "cos23.jpg",
    // size: V,
  },
  {
    id: "24",
    title:  "LET'S RIDE",
    source: "cos24.jpg",
    // size: BIG,
  },
  {
    id: "25",
    title:  "KEEPER OF THE GARDEN",
    source: "cos25.jpg",
    // size: BIG,
  },
  {
    id: "26",
    title:  "HERE",
    source: "cos25.jpg",
    // size: H,
  },
  {
    id: "27",
    title:  "THE HAMILTON GATEWAY",
    source: "cos27.jpg",
    // size: H,
  },
  {
    id: "28",
    title:  "THE AMERICAN CAPE",
    source: "cos28.jpg",
    // size: H,
  },
  {
    id: "29",
    title:  "CONVERSATION IN SIX PARTS",
    source: "cos29.jpg",
    // size: BIG,
  },
  {
    id: "30",
    title:  "COLLECTIVE IMPACT",
    source: "cos30.jpg",
    // size: V,
  },
  {
    id: "31",
    title:  "COME UNTO ME",
    source: "cos31.jpg",
    // size: H,
  },
  {
    id: "32",
    title:  "HANNA",
    source: "cos32.jpg",
    // size: BIG,
  },
  {
    id: "33",
    title:  "BRIDGE MEDALLIONS (1-4)",
    source: "cos33.jpg",
  },
  {
    id: "34",
    title:  "RIVERSIDE MALLARDS",
    source: "cos34.jpg",
    // size: V,
  },
  {
    id: "35",
    title:  "RIVER FLOOD MARKER",
    source: "cos35.jpg",
    // size: H,
  },
  {
    id: "36",
    title:  "FAMILY OF MAN",
    source: "cos36.jpg",
    // size: BIG,
  },
  {
    id: "37",
    title:  "TULIPS FOR THERESA BENCH",
    source: "cos37.jpg",
    // size: HUGE,
  },
  {
    id: "38",
    title:  "EMBRACE",
    source: "cos38.jpg",
    // size: H,
  },
  {
    id: "39",
    title:  "WHEN IT RAINS IT POURS",
    source: "cos39.jpg",
    // size: V,
  },
  {
    id: "40",
    title:  "BEETLE BENCH",
    source: "cos40.jpg",
    // size: V,
  },
  {
    id: "41",
    title:  "TWO HALVES OF A WHOLE",
    source: "cos41.jpg",
    // size: BIG,
  },
  {
    id: "42",
    title:  "SHERRY CORBET MEMORIAL",
    source: "cos42.jpg",
    // size: V,
  },
  {
    id: "43",
    title:  "SPACE TOWER",
    source: "cos43.jpg",
    // size: V,
  },
  {
    id: "44",
    title:  "BRIDGE MEDALLIONS (5-8)",
    source: "cos33.jpg",
    // size: V,
  },
  {
    id: "45",
    title:  "HELIOS GUARDIANS",
    source: "heliosGuardians.jpg",
    // size: BIG,
  },
  {
    id: "46",
    title:  "HOLE IN THE EARTH",
    source: "holeInTheEarth.jpg",
    // size: V,
  },
  {
    id: "47",
    title:  "LEARN AND GROW TOGETHER",
    source: "learnAndGrowTogether.jpg",
    // size: H,
  },
  {
    id: "48",
    title:  "MILLIKIN WOODS TOTEM POLE",
    source: "millikinWoodsTotemPole.jpg",
    // size: V,
  },
  {
    id: "49",
    title:  "NO CHILD LEFT BEHIND",
    source: "noChildLeftBehind.jpg",
    // size: V,
  },
  {
    id: "50",
    title:  "SPACE TOWER",
    source: "passages.jpg",
    // size: HUGE,
  },
  {
    id: "51",
    title:  "PEACE OFFICER MEMORIAL",
    source: "peaceOfficerMemorial.jpg",
    // size: H,
  },
  {
    id: "52",
    title:  "SOMEDAY",
    source: "someday.jpg",
    // size: H,
  },
  {
    id: "53",
    title:  "STAR FORMATION",
    source: "starFormation.jpg",
    // size: V,
  },
  {
    id: "54",
    title:  "THE HAPPY FAMILY",
    source: "theHappyFamily.jpg",
    // size: BIG,
  },
  {
    id: "55",
    title:  "TORRENT",
    source: "torrent.jpg",
    // size: BIG,
  },

  {
    id: "56",
    title:  "WILLOW",
    source: "willow.jpg",
    // size: V,
  },
  {
    id: "57",
    title:  "WIND FOREST",
    source: "windforest.jpg",
    // size: V,
  },

];