// const BIG = "big",
//   H = "horizontal",
//   V = "vertical",
//   HUGE = "huge";

export const listOfSculptures = [
  {
    id: "1",
    title:  "SPRING",
    source: "cos1.jpg",
    description:"A two figure life-sized bronze piece shows college-aged students situated in poses as if studying between classes. Created in 1979, it was installed in 1998, donated by Richard Fitton in honor of his parents.",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: HUGE,
  },
  {
    id: "2",
    title:  "SHARED VISION",
    source: "cos2.jpg",
    description:"Placed in 1997, a seated female figure in casual dress has sunglasses in her outstretched right hand. Her left hand holds her place in a book as shegestures as if offering the glasses,i.e. Shared Vision. ",
    artist:" Fred Brownstein",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: V,
  },
  {
    id: "3",
    title:  "FIRST RIDE",
    source: "cos3.jpg",
    description:"The work, by the internationally known sculptor, is a classic event: a girl, seated on a bicycle, attempting her first ride as her father stands proudly behind her.  Sponsored by the Carruthers family and unveiled in 1997. ",
    artist:" J. Seward Johnson, Jr.",
    address:"The Fitton Center, 101 Monument Ave.",
    // size: HUGE,
    },
  {
    id: "4",
    title:  "FIREFIGHTER MEMORIAL",
    source: "cos4.jpg",
    description:"The Butler County Fire Chiefs Association commissioned this memorial to those’lost in the line of duty. Public & private’donations paid for it along with the plaque honoring 15 Butler County’firefighters and EMTs who died’serving others.   ",
    artist:"George Danhires",
    address:"Pioneer Park, Monument Ave.",
    // size: H,
  },
  {
    id: "5",
    title:  "PIONEER FAMILY",
    source: "cos5.jpg",
    description:"Donated by Dr. John A. Stewart’and his wife, Marian Vail Stewart, to’commemorate the 200th anniversary of the Stewart family settling in Hamilton.  The faces are based on the Stewarts’at age 25. Installed September 2002. ",
    artist:" Jerry Hawkins",
    address:"Monument Cabin on Monument Ave.",
    // size: HUGE,
  },
  {
    id: "6",
    title:  "VICTORY",
    source: "cos6.jpg",
    description:" Victory, a 17’. 3500-lb. bronze Civil War soldier, was installed in 1906 on the Soldiers, Sailors, and Pioneers Monument.  His design was selected after a national competition.",
    artist:"Rudolph Thiem",
    address:"High St. & Monument Ave.",
    // size: V,
  },
  {
    id: "7",
    title:  "LEGACY OF LITERATURE",
    source: "cos7.jpg",
    description:"Purchased by Dr. & Mrs. James Stewart for the City of Sculpture, this bronze piece is a tribute to the thirst for knowledge through reading. The sculpture was installed April 2002 in the plaza at One High Street.",
    artist:"Rosalind Cook",
    address:"High St. at Monument Ave.",
    // size: BIG,
  },
  {
    id: "8",
    title:  "KITTY BENCH",
    source: "kittyBench.jpg",
    description:"Our collection also features a number of sculptural benches that can be found throughout the city, ranging in form from tulips to the more abstract Volkswagen Beetle, many of which were donated by families or in memory of loved ones. When you find one, take a moment to relax and check plaques near these one-of-a-kind pieces for more information. ",
    artist:" ",
    address:" ",
    // size: H,
  },
  {
    id: "9",
    title:  "DOUBLE CRAZY SWIRL",
    source: "cos9.jpg",
    description:"This is a colorful kinetic sculpture on a stainless steel base. Given to the City of Sculpture from Sherry Armstead and Symmetry Boutique.",
    artist:" Andrew Carson",
    address:"In front of the Visitor Center",
    // size: V,
  },
  {
    id: "10",
    title:  "LENTIL",
    source: "cos10.jpg",
    description:" In the 1940s children’s book by Hamilton native Robert McCloskey, Lentil parades through town, harmonica and dog in tow.  The Hamilton Community Foundation funded this as one of many permanent legacy gifts to the city.",
    artist:"Nancy Schon",
    address:"NW Corner - High at Front St.",
    // size: H,
  },
  {
    id: "11",
    title:  "SNAPSHOT",
    source: "cos11.jpg",
    description:" This life-size sculpture of seven children assembled to have their picture taken was commissioned by the Butler County Commissioners in September 2001.",
    artist:"Jane DeDecker",
    address:"County Administration Center, 130 High St.",
    // size: H,
  },
  {
    id: "12",
    title:  "URBAN RENEWAL",
    source: "cos12.jpg",
    description:" Local artist Nick Bauer contrasts Hamilton’s industrial past and bright future with the juxtaposition of the oxidized Cor-Ten base and use of stainless steel. This was purchased by Jim ",
    artist:"Nick Bauer",
    address:"Market St. & 2nd",
    // size: V,
  },
  {
    id: "13",
    title:  "PARK PLACE",
    source: "cos13.jpg",
    description:"This installation of 6 life-sized figures was created by world-famous artist, Glenna Goodacre. The artist brings her sense of fun to this interactive piece donated in 2007 by Sarah and Joe Marcum. ",
    artist:"Glenna Goodacre",
    address:"SW Corner of the High/Main St. Bridge",
    // size: H,
  },
  {
    id: "14",
    title:  "RESURGENCE",
    source: "cos14.jpg",
    description:"This welded metal sculpture was the winner of an Open Call to Artists competition in 2009. The sculptor took home the grand prize of $10,000 from the Outdoor Sculpture Exhibition. ",
    artist:" Jonathan Hils",
    address:"RiversEdge",
    // size: BIG,
  },
  {
    id: "15",
    title:  "4 PEOPLE",
    source: "cos15.jpg",
    description:"This Cor-Ten piece was purchased with proceeds from IceFest and is intended to depict family, community, and togetherness. The sculpture stands nearly 7’ tall at its peak and is 15’ wide. ",
    artist:"Dale Rogers",
    address:"RiversEdge",
    // size: H,
  },
  {
    id: "16",
    title:  "GUITAR",
    source: "cos16.jpg",
    description:"'Guitar' was a gift to the park from Gerry Hammond, one of the founding members of the City of Sculpture, in memory of her late husband and noted architect, Gerald S. Hammond. It is perfectly located next to the RiversEdge stage! ",
    artist:"Dale Rogers",
    address:"RiversEdge",
    // size: V,
  },
  {
    id: "17",
    title:  "MARCUM IN THE PARK",
    source: "cos17.jpg",
    description:"Stephen Marcum, an amateur artist and son of donors Joe and Sarah Marcum, designed the piece with his parents’ last name and generous hearts in mind. Stewart Iron Works fabricated this stainless steel sculpture.",
    artist:"Stephen Marcum",
    address:"Marcum Park",
    // size: V,
  },
  {
    id: "18",
    title:  "DOUBLE DANCER",
    source: "cos18.jpg",
    description:"Commissioned by the City of Sculpture,’this piece suggests two people, male’and female, merging into one person through dance. A more psychological’perspective is seeing the masculine’and feminine sides of everyone.",
    artist:"Dennis Sohocki",
    address:"YWCA, 244 Dayton St.",
    // size: BIG,
  },
  // {
  //   id: "19",
  //   title:  "TREE BENCH",
  //   source: "cos19.jpg",
  //   description:" ",
  //   artist:" ",
  //   address:" ",
  //   // size: H,
  // },
  {
    id: "20",
    title:  "THE MAESTRO:Lou Armstead Memorial",
    source: "cos20.jpg",
    description:"Purchased by the City of Sculpture and YMCA this laser cut steel sculpture is a representation of the late Lou Armstead, a beloved spinning instructor at the YMCA.",
    artist:"Nick Bauer",
    address:"Front of YMCA, 105 N. 2nd St",
    // size: H,
  },
  {
    id: "21",
    title:  "BIRD HOUSE",
    source: "cos21.jpg",
    description:" This painted aluminum form combines strong angles and a heavy rounded base. The color and form resonates with the surrounding park and nearby mural. The art was purchased with proceeds from City of Sculpture fundraisers.",
    artist:"Andrew Arvanetes",
    address:"Rotary Park",
    // size: V,
  },
  {
    id: "22",
    title:  "REPUBLIC CAR",
    source: "cos22.jpg",
    description:"Donated by The Antique & Classic Car Club of Butler Co. to commemorate a car manufactured in Hamilton, Ohio from 1909 to 1914. The painted metal sculpture is split in half so that people can get inside for a photo opportunity.",
    artist:"Paul Lashua",
    address:"Rotary Park",
    // size: H,
  },
  {
    id: "23",
    title:  "A FOREST TREASURE",
    source: "cos23.jpg",
    description:"As a figurative aluminum piece, A Forest Treasure features an impressive scale of 7’ in both height and girth. This whimsical flower was purchased with proceeds from City of Sculpture fundraisers and was installed in April of 2019. ",
    artist:"Douglas Gruizenga",
    address:"Rotary Park",
    // size: V,
  },
  {
    id: "24",
    title:  "LET'S RIDE",
    source: "cos24.jpg",
    description:"This is a one-of-a-kind piece designed by Akron, Ohio artist Don Drumm for Sherry Armstead, who opened Art Off Symmes. The store was the first new retail space on High St. at the beginning of Hamilton’s Renaissance in 2011. ",
    artist:"Don Drumm",
    address:"High St.",
    // size: BIG,
  },
  {
    id: "25",
    title:  "KEEPER OF THE GARDEN",
    source: "cos25.jpg",
    description:"The City of Sculpture purchased and placed this artwork in spring of 2005. This unusual handcarved Indiana limestone sculpture stands watch over a small reflection garden among the bustle and traffic of downtown. ",
    artist:"Daryl Johns",
    address:"First Financial Bank, High St.",
    // size: BIG,
  },
  {
    id: "26",
    title:  "HERE",
    source: "cos26.jpg",
    description:" ",
    artist:" ",
    address:" ",
    // size: H,
  },
  {
    id: "27",
    title:  "THE HAMILTON GATEWAY",
    source: "cos27.jpg",
    description:"A signature 66’ design, forward-looking and celebratory, heralds a ceremonial entry to downtown. This sculpture was dedicated at the then-new Government Square in 2000 and made possible by Judge John and Shirley Moser. ",
    artist:"Andrea Myklebust & Stanton G. Sears",
    address:"345 High St.",
    // size: H,
  },
  {
    id: "28",
    title:  "THE AMERICAN CAPE",
    source: "cos28.jpg",
    description:"Majestically standing 13’ high, this signature bronze of Alexander Hamilton, the city’s namesake, was commissioned jointly by City of Sculpture and Historic Hamilton, Inc.  The $230,000 sculpture was dedicated in October 2004. ",
    artist:"Kristen Visbal",
    address:"Middle of High St. at Journal Square",
    // size: H,
  },
  {
    id: "29",
    title:  "CONVERSATION IN SIX PARTS",
    source: "cos29.jpg",
    description:"The abstract stainless steel & bronze sculpture was purchased with a contribution from Cox Publishing and proceeds from IceFest 2009. The 6 interlocking curvilinear sections have a dynamic interplay suggesting an animated conversation. ",
    artist:"Eric David Laxman",
    address:"Journal Square",
    // size: BIG,
  },
  {
    id: "30",
    title:  "COLLECTIVE IMPACT",
    source: "cos30.jpg",
    description:"This stainless steel sculpture is an abstract representation of Community First Solutions positive role in providing health and education services to Butler County. Installed at their new downtown headquarters in 2015. ",
    artist:"John Leon",
    address:"230 Ludlow St.",
    // size: V,
  },
  {
    id: "31",
    title:  "COME UNTO ME",
    source: "cos31.jpg",
    description:"This bronze is an interactive sculpture of Jesus calling to children. A child on one knee, the other is open for children to sit on His lap. The sculpture was unveiled in August 2003 and purchased through congregational donations.",
    artist:"Rosalind Cook",
    address:"The Presbyterian Church, 19 S. Front St.",
    // size: H,
  },
  {
    id: "32",
    title:  "HANNA",
    source: "cos32.jpg",
    description:"Installed June 16, 2002, at The Presbyterian Creative Center for Children and dedicated to the memory of Robert Brown, this sculpture was generously funded by his friends and family. ",
    artist:"L’Deanne Trueblood",
    address:"23 Court St.",
    // size: BIG,
  },
  {
    id: "33",
    title:  "BRIDGE MEDALLIONS (1-4)",
    source: "cos33.jpg",
    description:" ",
    artist:" ",
    address:" ",
  },
  {
    id: "34",
    title:  "RIVERSIDE MALLARDS",
    source: "cos34.jpg",
    description:"Purchased by the City of Sculpture with proceeds from its biennial IceFest, this bronze was dedicated in the spring of 2007 for a newly created green space adjacent to the High/Main Bridge. ",
    artist:"Ronnie Wells",
    address:"Northwest corner of the’High, Main St. Bridge",
    // size: V,
  },
  {
    id: "35",
    title:  "RIVER FLOOD MARKER",
    source: "cos35.jpg",
    description:"The stainless steel sculpture marks the level of the floodwater during the 1913 flood and was donated by the City of Sculpture, Curtis & Celia Ellison, Genevieve O’Malley Knight, and Hamilton Journal News. ",
    artist:"John Hoskins",
    address:"On the “B” St. Ramp",
    // size: H,
  },
  {
    id: "36",
    title:  "FAMILY OF MAN",
    source: "cos36.jpg",
    description:" This painted steel piece was purchased by multiple donors in memory of the late Mrs. Jean Wolf. The sculpture is cut from a single piece of steel plate representing Mother Earth and the figures represent maturity, wisdom, and experience.",
    artist:"Cynthia McKean",
    address:"Park Ave. ramp",
    // size: BIG,
  },
  {
    id: "37",
    title:  "TULIPS FOR THERESA BENCH",
    source: "tulipBench.jpg",
    description:"Our collection also features a number of sculptural benches that can be found throughout the city, ranging in form from tulips to the more abstract Volkswagen Beetle, many of which were donated by families or in memory of loved ones. When you find one, take a moment to relax and check plaques near these one-of-a-kind pieces for more information. ",
    artist:" ",
    address:" ",
    // size: HUGE,
  },
  {
    id: "38",
    title:  "EMBRACE",
    source: "cos38.jpg",
    description:"Commemorating the 20th anniversary of the City of Sculpture, this abstract brushed stainless steel piece is more than 25’ tall and is symbolic of working together for a greater good. The sculpture was made possible by a group of generous community donors along with proceeds from IceFest. ",
    artist:"Hunter Brown",
    address:"Intersection of Main, Millville, and Eaton",
  },
  {
    id: "39",
    title:  "WHEN IT RAINS IT POURS",
    source: "cos39.jpg",
    description:"This bronze water sculpture greets pedestrians and motorists passing Armstead Park. Through collaboration between the Main Street Association and the City of Sculpture, this piece was dedicated on May 12, 2006.",
    artist:"Miles Metzger",
    address:"Armstead Park, Main & “D” Streets",
    // size: V,
  },
  {
    id: "40",
    title:  "BEETLE BENCH",
    source: "carBench.jpg",
    description:"Our collection also features a number of sculptural benches that can be found throughout the city, ranging in form from tulips to the more abstract Volkswagen Beetle, many of which were donated by families or in memory of loved ones. When you find one, take a moment to relax and check plaques near these one-of-a-kind pieces for more information. ",
    artist:"",
    address:"",
    // size: V,
  },
  {
    id: "41",
    title:  "TWO HALVES OF A WHOLE",
    source: "cos41.jpg",
    description:"This piece, created from two pieces of painted steel, was purchased by the City of Sculpture in honor and memory of the late Ray Miller, the artist and former board member, in 2009.",
    artist:"Ray Miller",
    address:"SE Corner of Main & B St.",
    // size: BIG,
  },
  {
    id: "42",
    title:  "SHERRY CORBET MEMORIAL",
    source: "cos42.jpg",
    description:" ",
    artist:" ",
    address:" ",
    // size: V,
  },
  {
    id: "43",
    title:  "SPACE TOWER",
    source: "cos43.jpg",
    description:"Originally created for Cincinnati Playhouse in the Park, where it stood for 10 years, this piece was inspired by the American space program and placed in 1980. ",
    artist:"Edgar Tafur",
    address:"Peter Rentschler Park, Ross Ave. & “B” St.",
    // size: V,
  },
  {
    id: "44",
    title:  "BRIDGE MEDALLIONS (5-8)",
    source: "cos33.jpg",
    description:" ",
    artist:" ",
    address:" ",
    // size: V,
  },
  {
    id: "45",
    title:  "HELIOS GUARDIANS",
    source: "heliosGuardians.jpg",
    description:"This 20’ tall modern sculpture once adorned the Cincinnati Zoo and Botanical Gardens.  It was purchased by the City of Sculpture in 2006, refurbished, and overlooks a small pond and garden. ",
    artist:"Michael Bigger",
    address:"Miami Woods Park, New London Rd.",
    // size: BIG,
  },
  {
    id: "46",
    title:  "HOLE IN THE EARTH",
    source: "holeInTheEarth.jpg",
    description:"Erected in 1873, this is potentially the first piece of public art in Hamilton. It commemorates John C. Symmes, one-time resident of Butler County, and his Hollow Earth theory. ",
    artist:"Unknown",
    address:"Symmes Park, Third & Ludlow Streets ",
    // size: V,
  },
  {
    id: "47",
    title:  "LEARN AND GROW TOGETHER",
    source: "learnAndGrowTogether.jpg",
    description:"This bronze honors Kathy Jackman, founder of the Community Preparatory School at Westover Retirement Community. The sculpture recognizes and celebrates the important link between generations.  ",
    artist:"John Leon",
    address:"Preparatory School at Westover, 855 Stahlheber Rd.",
    // size: H,
  },
  {
    id: "48",
    title:  "MILLIKIN WOODS TOTEM POLE",
    source: "millikinWoodsTotemPole.jpg",
    description:"A dying tree in one of our local parks was transformed into a nature themed totem by an artist who regularly carved during IceFest. This work was paid for by the City of Sculpture and Hamilton Parks Conservancy. ",
    artist:"Jonathon Michael (and Brady Lantz)",
    address:"Millikin Woods Park",
    // size: V,
  },
  {
    id: "49",
    title:  "NO CHILD LEFT BEHIND",
    source: "noChildLeftBehind.jpg",
    description:"Commemorating President George W. Bush’s signing of the education bill at Hamilton High School on January 8, 2002, and funded by a grant from Mr. and Mrs. Ralph Carruthers of Hamilton. ",
    artist:"Jarrett Hawkins",
    address:"Hamilton High School, 1165 Eaton Ave.",
    // size: V,
  },
  {
    id: "50",
    title:  "PASSAGES",
    source: "passages.jpg",
    description:"The distinctive sculptural relief is on the exterior of Parrish Auditorium and was a gift from Mr. & Mrs. Huntington V. Parrish.  The artist was a former faculty member. Dedicated in December 1973. ",
    artist:"Phillip Joseph",
    address:"MU Hamilton Campus, 1601 Peck Blvd.",
    // size: HUGE,
  },
  {
    id: "51",
    title:  "PEACE OFFICER MEMORIAL",
    source: "peaceOfficerMemorial.jpg",
    description:"The bronze statue depicts  Arthur Walke, the first Butler County officer killed in the line of duty.  He stands on an engraved granite wall and was dedicated in 2002.",
    artist:"Andrea Myklebust & Stanton G. Sears",
    address:"Butler County Justice Center, 705 Hanover St.",
    // size: H,
  },
  {
    id: "52",
    title:  "SOMEDAY",
    source: "someday.jpg",
    description:"Overlooking the first tee box, Someday  was dedicated in April 2002. It was created as a tribute to love of golf: Someday maybe I could be a pro… or someday maybe I could make a hole-in-one.",
    artist:"Rosalind Cook",
    address:"Potters Golf Course,’417 New London Rd.",
    // size: H,
  },
  {
    id: "53",
    title:  "STAR FORMATION",
    source: "starFormation.jpg",
    description:"A 20’ tall abstract of stainless steel, this piece was installed in August 2002 and commissioned by the City of Sculpture.",
    artist:"Dennis Baker, Hamilton Artist-in-Residence",
    address:"Monument Ave.",
    // size: V,
  },
  {
    id: "54",
    title:  "THE HAPPY FAMILY",
    source: "theHappyFamily.jpg",
    description:"Honoring 75 years of service to the community by Ft. Hamilton Hospital, and saluting all who work to celebrate life, this bronze was commissioned by Dr. & Mrs. James Stewart. ",
    artist:"Alfred Tibor",
    address:"Ft. Hamilton Hospital, 630 Eaton Ave.",
    // size: BIG,
  },
  {
    id: "55",
    title:  "TORRENT",
    source: "torrent.jpg",    
    description:"Originally sculpted in June 2005, Torrent is a forged aluminum piece that incorporates glass elements. This one-of-a-kind sculpture was purchased by the Hamilton Rotary Club in 2007. ",
    artist:"Brian F. Russell",
    address:"Marriott Hotel courtyard along the bike path",
    // size: BIG,
  },

  {
    id: "56",
    title:  "WILLOW",
    source: "willow.jpg",
    description:"This spinning garden kaleidoscope is made from powder coated steel. The sculpture was donated by the City of Sculpture and friends of Miami University Hamilton. ",
    artist:"Robert Anderson",
    address:"MUH Conservatory area",
    // size: V,
  },
  {
    id: "57",
    title:  "WIND FOREST",
    source: "windforest.jpg",
    description:"According to the artist, People love wind sculptures. A calming force, they provide serenity in a world of confusion. The City of Sculpture commissioned these pieces which were dedicated in March 2002.",
    artist:"Lyman Whitaker",
    address:"Dam Overlook, Neilan Blvd.",
    // size: V,
  },

];